"""add_keyword_expansion_tables

Revision ID: 493bb1bc3261
Revises: 604d29be56c9
Create Date: 2026-02-09 13:03:53.689139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493bb1bc3261'
down_revision: Union[str, None] = '604d29be56c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_relationships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_keyword_id', sa.Integer(), nullable=False),
        sa.Column('target_keyword_id', sa.Integer(), nullable=False),
        sa.Column('relationship_type', sa.String(length=50), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('discovery_method', sa.String(length=50), nullable=False),
        sa.Column('geo', sa.String(length=5), nullable=False),
        sa.Column('time_period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('time_period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cooccurrence_count', sa.Integer(), nullable=True),
        sa.Column('correlation_coefficient', sa.Float(), nullable=True),
        sa.Column('shared_words', sa.Text(), nullable=True),
        sa.Column('first_discovered', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.ForeignKeyConstraint(['source_keyword_id'], ['trend_keywords.id'], ),
        sa.ForeignKeyConstraint(['target_keyword_id'], ['trend_keywords.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_keyword_id', 'target_keyword_id', 'relationship_type', name='unique_keyword_relationship')
    )
    op.create_index('idx_keyword_relationships_geo_type', 'keyword_relationships', ['geo', 'relationship_type'], unique=False)
    op.create_index('idx_keyword_relationships_type_score', 'keyword_relationships', ['relationship_type', 'confidence_score'], unique=False)
    op.create_index('idx_keyword_relationships_updated', 'keyword_relationships', ['last_updated'], unique=False)
    op.create_index('ix_keyword_relationships_source_keyword_id', 'keyword_relationships', ['source_keyword_id'], unique=False)
    op.create_index('ix_keyword_relationships_target_keyword_id', 'keyword_relationships', ['target_keyword_id'], unique=False)

    op.create_table('keyword_clusters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('centroid_keyword_id', sa.Integer(), nullable=False),
        sa.Column('cluster_size', sa.Integer(), nullable=False),
        sa.Column('cohesion_score', sa.Float(), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('geo', sa.String(length=5), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.ForeignKeyConstraint(['centroid_keyword_id'], ['trend_keywords.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_clusters_centroid', 'keyword_clusters', ['centroid_keyword_id'], unique=False)
    op.create_index('idx_keyword_clusters_geo_category', 'keyword_clusters', ['geo', 'category'], unique=False)
    op.create_index('idx_keyword_clusters_updated', 'keyword_clusters', ['last_updated'], unique=False)
    op.create_index('ix_keyword_clusters_centroid_keyword_id', 'keyword_clusters', ['centroid_keyword_id'], unique=False)

    op.create_table('keyword_cluster_memberships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keyword_id', sa.Integer(), nullable=False),
        sa.Column('cluster_id', sa.Integer(), nullable=False),
        sa.Column('membership_strength', sa.Float(), nullable=False),
        sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], ),
        sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('keyword_id', 'cluster_id', name='unique_keyword_cluster_membership')
    )
    op.create_index('idx_keyword_cluster_memberships_cluster', 'keyword_cluster_memberships', ['cluster_id'], unique=False)
    op.create_index('idx_keyword_cluster_memberships_keyword', 'keyword_cluster_memberships', ['keyword_id'], unique=False)
    op.create_index('ix_keyword_cluster_memberships_cluster_id', 'keyword_cluster_memberships', ['cluster_id'], unique=False)
    op.create_index('ix_keyword_cluster_memberships_keyword_id', 'keyword_cluster_memberships', ['keyword_id'], unique=False)

    op.create_table('keyword_expansion_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cache_key', sa.String(length=255), nullable=False),
        sa.Column('suggestions', sa.Text(), nullable=False),
        sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cache_key')
    )
    op.create_index('idx_keyword_expansion_cache_expires', 'keyword_expansion_cache', ['expires_at'], unique=False)
    op.create_index('ix_keyword_expansion_cache_cache_key', 'keyword_expansion_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_keyword_expansion_cache_cache_key', table_name='keyword_expansion_cache')
    op.drop_index('idx_keyword_expansion_cache_expires', table_name='keyword_expansion_cache')
    op.drop_table('keyword_expansion_cache')
    op.drop_index('ix_keyword_cluster_memberships_keyword_id', table_name='keyword_cluster_memberships')
    op.drop_index('ix_keyword_cluster_memberships_cluster_id', table_name='keyword_cluster_memberships')
    op.drop_index('idx_keyword_cluster_memberships_keyword', table_name='keyword_cluster_memberships')
    op.drop_index('idx_keyword_cluster_memberships_cluster', table_name='keyword_cluster_memberships')
    op.drop_table('keyword_cluster_memberships')
    op.drop_index('ix_keyword_clusters_centroid_keyword_id', table_name='keyword_clusters')
    op.drop_index('idx_keyword_clusters_updated', table_name='keyword_clusters')
    op.drop_index('idx_keyword_clusters_geo_category', table_name='keyword_clusters')
    op.drop_index('idx_keyword_clusters_centroid', table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index('ix_keyword_relationships_target_keyword_id', table_name='keyword_relationships')
    op.drop_index('ix_keyword_relationships_source_keyword_id', table_name='keyword_relationships')
    op.drop_index('idx_keyword_relationships_updated', table_name='keyword_relationships')
    op.drop_index('idx_keyword_relationships_type_score', table_name='keyword_relationships')
    op.drop_index('idx_keyword_relationships_geo_type', table_name='keyword_relationships')
    op.drop_table('keyword_relationships')
    # ### end Alembic commands ###
