"""Add alert rule analytics table

Revision ID: 604d29be56c9
Revises: 11ba5cefdf8e
Create Date: 2026-02-09 12:20:59.320072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604d29be56c9'
down_revision: Union[str, None] = '11ba5cefdf8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False, comment='Login username (unique, case-insensitive enforced at app level)'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Email address for notifications and password recovery'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='bcrypt-hashed password (never store plaintext)'),
    sa.Column('display_name', sa.String(length=256), nullable=False, comment='Human-readable display name'),
    sa.Column('role', sa.String(length=32), server_default='analyst', nullable=False, comment='Authorization role: admin | analyst | viewer'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag — inactive users cannot log in'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='alert'
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True, schema='alert')
    op.create_index('ix_user_username', 'user', ['username'], unique=True, schema='alert')
    op.create_table('alert_template',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable name for the template'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of when to use this template'),
    sa.Column('subject_template', sa.String(length=255), nullable=False, comment='Jinja2 template for email subject line'),
    sa.Column('html_template', sa.Text(), nullable=False, comment='Jinja2 template for HTML email body'),
    sa.Column('text_template', sa.Text(), nullable=False, comment='Jinja2 template for plain text email body'),
    sa.Column('severity_filter', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Severities this template applies to (empty = all severities)'),
    sa.Column('category_filter', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Categories this template applies to (empty = all categories)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default template for matching alerts'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Whether this is a system template (cannot be deleted)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this template is active'),
    sa.Column('template_metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional template configuration (CSS, images, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    comment='Customizable alert notification templates'
    )
    op.create_index('ix_alert_template_is_default', 'alert_template', ['is_default'], unique=False)
    op.create_index('ix_alert_template_name', 'alert_template', ['name'], unique=False)
    op.create_table('backtest_run',
    sa.Column('name', sa.String(length=256), nullable=False, comment="Human-readable name, e.g. '2023 Banking Stress replay'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='Historical replay starts here'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='Historical replay ends here'),
    sa.Column('parameters', postgresql.JSONB(astext_type=Text()), nullable=False, comment='Full parameter snapshot (thresholds, weights, etc.)'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus'), nullable=False, comment='pending → running → completed / failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Total alerts produced during replay'),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('missed_events', sa.Integer(), nullable=False, comment='Known real events that were NOT flagged'),
    sa.Column('results_summary', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Extended metrics: precision, recall, F1, lead-time dist'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    schema='backtest',
    comment='Synthetic backtest execution records'
    )
    op.create_index('ix_backtest_status', 'backtest_run', ['status'], unique=False, schema='backtest')
    op.create_table('source_registry',
    sa.Column('name', sa.String(length=128), nullable=False, comment="Human-readable source name, e.g. 'google_trends'"),
    sa.Column('source_type', sa.Enum('SEARCH', 'WIKI', 'SOCIAL', 'NEWS', 'FINANCE', 'HEALTH', 'ALT_DATA', name='sourcetype'), nullable=False, comment='Broad category: search / wiki / social / news / …'),
    sa.Column('description', sa.Text(), nullable=True, comment='Free-text notes about the source'),
    sa.Column('api_endpoint', sa.String(length=1024), nullable=True, comment='Base URL or ARN of the external API'),
    sa.Column('auth_method', sa.String(length=64), nullable=True, comment='oauth2 | api_key | iam_role | none'),
    sa.Column('update_frequency_seconds', sa.Integer(), nullable=False, comment='How often (seconds) the connector runs'),
    sa.Column('data_latency_seconds', sa.Integer(), nullable=False, comment='Typical delay between real-world event and availability'),
    sa.Column('health_status', sa.Enum('LIVE', 'DEGRADED', 'DOWN', name='healthstatus'), nullable=False, comment='Current operational state: live / degraded / down'),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful data pull'),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False, comment='Rolling failure count; resets on success'),
    sa.Column('default_weight', sa.Float(), nullable=False, comment='Baseline weight used in ensemble confidence scoring'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Master on/off switch for this connector'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_source_name'),
    schema='ingestion',
    comment='Catalogue of all data sources'
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('email_subject_template', sa.String(length=255), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_time', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('email_recipients', sa.JSON(), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_cluster',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the observation window'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='End of the observation window'),
    sa.Column('label', sa.String(length=256), nullable=True, comment='Auto-generated or analyst-assigned cluster label'),
    sa.Column('centroid_vector', postgresql.ARRAY(Float()), nullable=False, comment='Mean SBERT embedding vector (768-d or 384-d)'),
    sa.Column('cluster_size', sa.Integer(), nullable=False, comment='Number of unique entities in this cluster'),
    sa.Column('drift_score', sa.Float(), nullable=False, comment='Cosine distance the centroid moved since the prior window'),
    sa.Column('drift_flag', sa.Boolean(), nullable=False, comment='True when drift exceeds threshold (rapid semantic shift)'),
    sa.Column('prior_cluster_id', sa.UUID(), nullable=True, comment='The same logical cluster from the previous time window'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['prior_cluster_id'], ['signal.semantic_cluster.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='signal',
    comment='SBERT topic clusters with drift tracking'
    )
    op.create_index('ix_cluster_drift', 'semantic_cluster', ['drift_score'], unique=False, schema='signal')
    op.create_table('trend_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('current_rank', sa.Integer(), nullable=True),
    sa.Column('current_traffic', sa.String(length=50), nullable=True),
    sa.Column('current_traffic_value', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peak_rank', sa.Integer(), nullable=True),
    sa.Column('total_appearances', sa.Integer(), nullable=False),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('velocity_trend', sa.JSON(), nullable=True),
    sa.Column('direction_changes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_keywords_category', 'trend_keywords', ['category'], unique=False)
    op.create_index('idx_trend_keywords_keyword_geo', 'trend_keywords', ['keyword', 'geo'], unique=False)
    op.create_index('idx_trend_keywords_last_seen', 'trend_keywords', ['last_seen'], unique=False)
    op.create_index(op.f('ix_trend_keywords_geo'), 'trend_keywords', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_keywords_keyword'), 'trend_keywords', ['keyword'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_trends', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('trends_data', sa.JSON(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('rate_limited', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_snapshots_captured', 'trend_snapshots', ['captured_at'], unique=False)
    op.create_index('idx_trend_snapshots_geo_captured', 'trend_snapshots', ['geo', 'captured_at'], unique=False)
    op.create_index(op.f('ix_trend_snapshots_geo'), 'trend_snapshots', ['geo'], unique=False)
    op.create_table('alert_rule_analytics',
    sa.Column('rule_id', sa.UUID(), nullable=False, comment='The alert rule being analyzed'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the analytics period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of the analytics period'),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Total alerts generated by this rule in the period'),
    sa.Column('alerts_confirmed', sa.Integer(), nullable=False, comment='Alerts confirmed as true positives'),
    sa.Column('alerts_dismissed', sa.Integer(), nullable=False, comment='Alerts dismissed as false positives'),
    sa.Column('alerts_escalated', sa.Integer(), nullable=False, comment='Alerts that were escalated'),
    sa.Column('average_response_time_minutes', sa.Float(), nullable=True, comment='Average time from alert creation to resolution (minutes)'),
    sa.Column('precision_score', sa.Float(), nullable=True, comment='Precision: confirmed / (confirmed + dismissed)'),
    sa.Column('recall_score', sa.Float(), nullable=True, comment='Recall: confirmed / total relevant events (if available)'),
    sa.Column('effectiveness_score', sa.Float(), nullable=True, comment='Overall effectiveness score (0-1)'),
    sa.Column('false_positive_rate', sa.Float(), nullable=True, comment='False positive rate: dismissed / total alerts'),
    sa.Column('alert_volume_trend', sa.Float(), nullable=True, comment='Trend in alert volume (+/- percentage change)'),
    sa.Column('analytics_metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional analytics data (severity distribution, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert.alert_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Performance analytics for alert rules'
    )
    op.create_index('ix_alert_rule_analytics_period', 'alert_rule_analytics', ['period_start', 'period_end'], unique=False, schema='alert')
    op.create_index('ix_alert_rule_analytics_rule_id', 'alert_rule_analytics', ['rule_id'], unique=False, schema='alert')
    op.create_table('raw_ingestion',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Which source produced this payload'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When VanguardSignal received this data'),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False, comment='Complete API response body stored as JSONB'),
    sa.Column('payload_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw payload bytes'),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False, comment='Byte length of the original payload'),
    sa.Column('schema_version', sa.String(length=32), nullable=False, comment='Version tag for the upstream API schema'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='False if schema validation failed at ingest'),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Structured list of validation failures, if any'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion',
    comment='Immutable raw API payloads'
    )
    op.create_index('ix_raw_source_time', 'raw_ingestion', ['source_id', 'ingested_at'], unique=False, schema='ingestion')
    op.create_table('semantic_cluster_member',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The search term, page title, etc.'),
    sa.Column('embedding_vector', postgresql.ARRAY(Float()), nullable=True, comment="This entity's individual SBERT embedding"),
    sa.Column('distance_to_centroid', sa.Float(), nullable=False, comment='Cosine distance from entity embedding to cluster centroid'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['cluster_id'], ['signal.semantic_cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'entity_value', name='uq_cluster_entity'),
    schema='signal',
    comment='Entity membership in semantic clusters'
    )
    op.create_table('signal_time_series',
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='Search term, page title, etc.'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Which source produced this series'),
    sa.Column('bucket_size', sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', name='timebucket'), nullable=False, comment='Aggregation granularity: hour / day / week / month'),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False, comment='Inclusive start of this time bucket'),
    sa.Column('bucket_end', sa.DateTime(timezone=True), nullable=False, comment='Exclusive end of this time bucket'),
    sa.Column('value', sa.Float(), nullable=False, comment='Aggregated metric (mean interest, total views, …)'),
    sa.Column('sample_count', sa.Integer(), nullable=False, comment='Number of NormalizedEvents that were aggregated'),
    sa.Column('coverage_score', sa.Float(), nullable=False, comment='1.0 = full data; <1.0 = degraded coverage'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_value', 'source_id', 'bucket_size', 'bucket_start', name='uq_signal_entity_bucket'),
    schema='signal',
    comment='Aggregated time-series per entity'
    )
    op.create_index('ix_signal_entity_time', 'signal_time_series', ['entity_value', 'bucket_start'], unique=False, schema='signal')
    op.create_index('ix_signal_source_bucket', 'signal_time_series', ['source_id', 'bucket_start'], unique=False, schema='signal')
    op.create_table('trend_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rank_at_alert', sa.Integer(), nullable=True),
    sa.Column('interest_at_alert', sa.Float(), nullable=True),
    sa.Column('velocity_at_alert', sa.Float(), nullable=True),
    sa.Column('pct_change_24h', sa.Float(), nullable=True),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('related_news', sa.JSON(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_alerts_keyword_triggered', 'trend_alerts', ['keyword_id', 'triggered_at'], unique=False)
    op.create_index('idx_trend_alerts_severity', 'trend_alerts', ['severity'], unique=False)
    op.create_index('idx_trend_alerts_type_triggered', 'trend_alerts', ['alert_type', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_trend_alerts_geo'), 'trend_alerts', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_alerts_keyword_id'), 'trend_alerts', ['keyword_id'], unique=False)
    op.create_table('trend_time_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interest_score', sa.Float(), nullable=False),
    sa.Column('rank_at_time', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_time_series_geo_timestamp', 'trend_time_series', ['geo', 'timestamp'], unique=False)
    op.create_index('idx_trend_time_series_keyword_timestamp', 'trend_time_series', ['keyword_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trend_time_series_geo'), 'trend_time_series', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_time_series_keyword_id'), 'trend_time_series', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_trend_time_series_timestamp'), 'trend_time_series', ['timestamp'], unique=False)
    op.create_table('normalized_event',
    sa.Column('raw_id', sa.UUID(), nullable=False, comment='Link back to the immutable raw payload (audit trail)'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Denormalized source FK for fast filtering'),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False, comment='When the event actually occurred (source timestamp)'),
    sa.Column('entity_type', sa.Enum('SEARCH_QUERY', 'WIKI_PAGE', 'SOCIAL_POST', 'NEWS_HEADLINE', 'FINANCIAL_TICK', 'HEALTH_REPORT', name='entitytype'), nullable=False, comment='Kind of entity: search_query / wiki_page / …'),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The search term, page title, headline text, etc.'),
    sa.Column('metric_value', sa.Float(), nullable=False, comment='Numeric measure: search interest, page views, sentiment, …'),
    sa.Column('geo', sa.String(length=8), nullable=True, comment='ISO 3166-1 alpha-2 country code, if available'),
    sa.Column('language', sa.String(length=8), nullable=True, comment='ISO 639-1 language code, if available'),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Catch-all for source-specific fields not in the schema'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['raw_id'], ['ingestion.raw_ingestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion',
    comment='Cleaned, schema-conformant events'
    )
    op.create_index('ix_norm_entity_time', 'normalized_event', ['entity_type', 'event_time'], unique=False, schema='ingestion')
    op.create_index('ix_norm_entity_value', 'normalized_event', ['entity_value'], unique=False, schema='ingestion')
    op.create_index('ix_norm_source_time', 'normalized_event', ['source_id', 'event_time'], unique=False, schema='ingestion')
    op.create_table('anomaly_result',
    sa.Column('series_id', sa.UUID(), nullable=False, comment='The time-series bucket that was evaluated'),
    sa.Column('detection_time', sa.DateTime(timezone=True), nullable=False, comment='When this detection pass ran'),
    sa.Column('stl_trend', sa.Float(), nullable=True, comment='Trend component from STL decomposition'),
    sa.Column('stl_seasonal', sa.Float(), nullable=True, comment='Seasonal component from STL decomposition'),
    sa.Column('stl_residual', sa.Float(), nullable=True, comment='Residual after removing trend + seasonality'),
    sa.Column('stl_residual_zscore', sa.Float(), nullable=True, comment='Z-score of the residual (how many σ from mean)'),
    sa.Column('iforest_score', sa.Float(), nullable=True, comment='Isolation Forest anomaly score (−1 to 0 range typical)'),
    sa.Column('iforest_contamination', sa.Float(), nullable=True, comment='Contamination parameter used for this run'),
    sa.Column('cusum_score', sa.Float(), nullable=True, comment='CUSUM statistic; large values → sustained mean shift'),
    sa.Column('cusum_threshold', sa.Float(), nullable=True, comment='The threshold that was in effect for CUSUM'),
    sa.Column('cusum_drift', sa.Float(), nullable=True, comment='Allowable drift parameter used for this run'),
    sa.Column('velocity_score', sa.Float(), nullable=True, comment='Velocity detector normalised score (0–1); high = rapid acceleration'),
    sa.Column('velocity_acceleration', sa.Float(), nullable=True, comment='Raw second derivative (acceleration) at the latest point'),
    sa.Column('weight_stl', sa.Float(), nullable=False, comment='Weight assigned to STL Z-score in the ensemble'),
    sa.Column('weight_iforest', sa.Float(), nullable=False, comment='Weight assigned to Isolation Forest score'),
    sa.Column('weight_cusum', sa.Float(), nullable=False, comment='Weight assigned to CUSUM score'),
    sa.Column('weight_velocity', sa.Float(), nullable=False, comment='Weight assigned to Velocity detector score'),
    sa.Column('ensemble_score', sa.Float(), nullable=False, comment='Final combined anomaly score'),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False, comment='True when ensemble_score exceeds alert threshold'),
    sa.Column('ensemble_threshold', sa.Float(), nullable=False, comment='The threshold that was in effect for this decision'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['series_id'], ['signal.signal_time_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'detection_time', name='uq_anomaly_series_time'),
    schema='signal',
    comment='Per-bucket ensemble anomaly scores'
    )
    op.create_index('ix_anomaly_ensemble', 'anomaly_result', ['ensemble_score'], unique=False, schema='signal')
    op.create_index('ix_anomaly_flag', 'anomaly_result', ['is_anomaly'], unique=False, schema='signal')
    op.create_table('alert',
    sa.Column('primary_entity', sa.String(length=1024), nullable=False, comment='The entity (search term, page, …) at the center of the anomaly'),
    sa.Column('related_entities', postgresql.ARRAY(String()), nullable=True, comment='Other entities co-occurring in the same anomaly window'),
    sa.Column('anomaly_result_id', sa.UUID(), nullable=True, comment='The specific anomaly row that spawned this alert'),
    sa.Column('trigger_rule_id', sa.UUID(), nullable=True, comment='The alert rule that triggered this alert (if rule-based)'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False, comment='low / medium / high / critical'),
    sa.Column('status', sa.Enum('ACTIVE', 'WATCHING', 'CONFIRMED', 'DISMISSED', 'RESOLVED', 'ARCHIVED', name='alertstatus'), nullable=False, comment='Lifecycle: active → watching → confirmed/dismissed → resolved'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Final confidence (0.0 – 1.0)'),
    sa.Column('ensemble_anomaly_score', sa.Float(), nullable=False, comment="Anomaly engine's ensemble output"),
    sa.Column('source_weights', postgresql.JSONB(astext_type=Text()), nullable=False, comment='Per-source weight snapshot, e.g. {"google_trends": 0.6, "wikipedia": 0.4}'),
    sa.Column('semantic_drift_score', sa.Float(), nullable=False, comment='Semantic drift contribution (0.0 until Phase 2)'),
    sa.Column('reason_code', sa.String(length=128), nullable=False, comment='Machine-readable reason, e.g. CUSUM_SHIFT, STL_SPIKE, DRIFT'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='Auto-generated plain-English explanation for the analyst'),
    sa.Column('signal_start', sa.DateTime(timezone=True), nullable=False, comment='Earliest timestamp of the contributing anomaly window'),
    sa.Column('signal_end', sa.DateTime(timezone=True), nullable=False, comment='Latest timestamp of the contributing anomaly window'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['anomaly_result_id'], ['signal.anomaly_result.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['alert.alert_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Flagged anomalies for analyst review'
    )
    op.create_index('ix_alert_created', 'alert', ['created_at'], unique=False, schema='alert')
    op.create_index('ix_alert_severity', 'alert', ['severity'], unique=False, schema='alert')
    op.create_index('ix_alert_status', 'alert', ['status'], unique=False, schema='alert')
    op.create_table('alert_rule_trigger',
    sa.Column('rule_id', sa.UUID(), nullable=False, comment='The rule that was triggered'),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The entity (keyword, term) that triggered the rule'),
    sa.Column('geo', sa.String(length=5), nullable=False, comment='Geographic region where trigger occurred'),
    sa.Column('actual_value', sa.Float(), nullable=False, comment='The actual measured value that triggered the rule'),
    sa.Column('threshold_value', sa.Float(), nullable=False, comment='The threshold value that was exceeded'),
    sa.Column('alert_created', sa.Boolean(), nullable=False, comment='Whether an alert was actually created from this trigger'),
    sa.Column('alert_id', sa.UUID(), nullable=True, comment='The alert that was created (if any)'),
    sa.Column('trigger_metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional context about the trigger (time series data, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert.alert_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Tracks alert rule trigger history'
    )
    op.create_index('ix_alert_rule_trigger_cooldown', 'alert_rule_trigger', ['rule_id', 'entity_value', 'geo'], unique=False, schema='alert')
    op.create_index('ix_alert_rule_trigger_rule_triggered', 'alert_rule_trigger', ['rule_id', 'created_at'], unique=False, schema='alert')
    op.create_table('analyst_feedback',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False, comment="Analyst's identity (from auth provider)"),
    sa.Column('verdict', sa.Enum('CONFIRM', 'DISMISS', name='feedbackverdict'), nullable=False, comment='confirm or dismiss'),
    sa.Column('confidence', sa.Float(), nullable=True, comment="Analyst's self-reported confidence in the verdict (0–1)"),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional free-text reasoning'),
    sa.Column('was_used_for_training', sa.Boolean(), nullable=False, comment='True once the RL training loop has consumed this row'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Analyst confirm/dismiss verdicts'
    )
    op.create_index('ix_feedback_alert', 'analyst_feedback', ['alert_id'], unique=False, schema='alert')
    op.create_table('evidence_chain',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('raw_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of RawIngestion rows that contributed'),
    sa.Column('normalized_event_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of NormalizedEvent rows'),
    sa.Column('series_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of SignalTimeSeries rows'),
    sa.Column('anomaly_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of AnomalyResult rows'),
    sa.Column('explainability_text', sa.Text(), nullable=False, comment='Auto-generated narrative explaining how evidence connects'),
    sa.Column('evidence_metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional structured data for the evidence visualization'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Audit trail linking alerts to raw data'
    )
    op.create_index('ix_evidence_alert', 'evidence_chain', ['alert_id'], unique=False, schema='alert')
    op.create_table('historical_analog',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='The NEW alert we are providing context for'),
    sa.Column('matched_alert_id', sa.UUID(), nullable=False, comment='The HISTORICAL alert that looks similar'),
    sa.Column('similarity_score', sa.Float(), nullable=False, comment='0.0 (no match) – 1.0 (identical pattern)'),
    sa.Column('similarity_method', sa.String(length=64), nullable=False, comment='Algorithm used: dtw_cosine / euclidean / …'),
    sa.Column('reference_period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the historical reference window'),
    sa.Column('reference_period_end', sa.DateTime(timezone=True), nullable=False, comment='End of the historical reference window'),
    sa.Column('analog_summary', sa.Text(), nullable=True, comment='Plain-English description of the historical event'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Similar historical patterns for context'
    )
    op.create_index('ix_analog_alert', 'historical_analog', ['alert_id'], unique=False, schema='alert')
    op.create_table('post_mortem',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='One post-mortem per alert'),
    sa.Column('event_outcome', sa.Enum('TRUE_POSITIVE', 'FALSE_POSITIVE', 'INCONCLUSIVE', name='eventoutcome'), nullable=False, comment='true_positive / false_positive / inconclusive'),
    sa.Column('impact_domain', sa.Enum('FINANCE', 'GEOPOLITICAL', 'HEALTH', 'CIVIL_UNREST', 'CYBER', 'ENVIRONMENTAL', 'OTHER', name='impactdomain'), nullable=True, comment='finance / geopolitical / health / civil_unrest / …'),
    sa.Column('impact_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True, comment='Retrospective severity of the actual event'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Free-text analyst notes on what happened'),
    sa.Column('external_references', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Links to news articles, government reports, etc.'),
    sa.Column('event_actual_start', sa.DateTime(timezone=True), nullable=True, comment='When the real-world event actually began'),
    sa.Column('event_actual_end', sa.DateTime(timezone=True), nullable=True, comment='When the real-world event resolved'),
    sa.Column('lead_time_hours', sa.Float(), nullable=True, comment='Hours between alert creation and real-world event start'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id'),
    schema='alert',
    comment='Retrospective outcome labels for alerts'
    )
    op.create_index('ix_pm_outcome', 'post_mortem', ['event_outcome'], unique=False, schema='alert')
    op.create_table('alert_escalation',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='The alert that was escalated'),
    sa.Column('previous_severity', sa.String(length=20), nullable=False, comment='Severity before escalation (low/medium/high/critical)'),
    sa.Column('new_severity', sa.String(length=20), nullable=False, comment='Severity after escalation (low/medium/high/critical)'),
    sa.Column('escalation_reason', sa.Text(), nullable=True, comment='Human-readable explanation of why escalation occurred'),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False, comment='When the escalation occurred'),
    sa.Column('escalation_trigger', sa.String(length=50), nullable=True, comment="What triggered escalation: 'time_based', 'score_increase', 'repeated'"),
    sa.Column('escalation_metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional context (thresholds, time windows, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks automatic severity escalations for alerts'
    )
    op.create_index('ix_alert_escalation_alert_id', 'alert_escalation', ['alert_id'], unique=False)
    op.create_index('ix_alert_escalation_escalated_at', 'alert_escalation', ['escalated_at'], unique=False)
    op.create_index('ix_alert_escalation_trigger', 'alert_escalation', ['escalation_trigger'], unique=False)
    op.create_table('alert_silence',
    sa.Column('alert_id', sa.UUID(), nullable=True, comment='Specific alert to silence (null for pattern/global silences)'),
    sa.Column('entity_pattern', sa.String(length=1024), nullable=True, comment='Regex pattern to match entity names (for entity-based silencing)'),
    sa.Column('silenced_by', sa.String(length=256), nullable=False, comment='User who created the silence rule'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for silencing'),
    sa.Column('silence_type', sa.String(length=50), nullable=False, comment="Type of silence: 'alert', 'entity', 'global'"),
    sa.Column('silenced_at', sa.DateTime(timezone=True), nullable=False, comment='When the silence was created'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration in minutes (null for indefinite)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the silence expires'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this silence rule is currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks alert silencing/snoozing rules'
    )
    op.create_index('ix_alert_silence_alert_id', 'alert_silence', ['alert_id'], unique=False)
    op.create_index('ix_alert_silence_entity_pattern', 'alert_silence', ['entity_pattern'], unique=False)
    op.create_index('ix_alert_silence_expires_at', 'alert_silence', ['expires_at'], unique=False)
    op.create_index('ix_alert_silence_is_active', 'alert_silence', ['is_active'], unique=False)
    op.create_table('backtest_alert',
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('primary_entity', sa.String(length=1024), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ensemble_anomaly_score', sa.Float(), nullable=False),
    sa.Column('source_weights', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('signal_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_real_alert_id', sa.UUID(), nullable=True, comment='If this backtest alert matches a real historical alert'),
    sa.Column('is_true_positive', sa.Boolean(), nullable=True, comment='Did this correspond to a real event? (from PostMortem)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest.backtest_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_real_alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='backtest',
    comment='Hypothetical alerts from a backtest'
    )
    op.create_index('ix_bt_alert_run', 'backtest_alert', ['backtest_run_id'], unique=False, schema='backtest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bt_alert_run', table_name='backtest_alert', schema='backtest')
    op.drop_table('backtest_alert', schema='backtest')
    op.drop_index('ix_alert_silence_is_active', table_name='alert_silence')
    op.drop_index('ix_alert_silence_expires_at', table_name='alert_silence')
    op.drop_index('ix_alert_silence_entity_pattern', table_name='alert_silence')
    op.drop_index('ix_alert_silence_alert_id', table_name='alert_silence')
    op.drop_table('alert_silence')
    op.drop_index('ix_alert_escalation_trigger', table_name='alert_escalation')
    op.drop_index('ix_alert_escalation_escalated_at', table_name='alert_escalation')
    op.drop_index('ix_alert_escalation_alert_id', table_name='alert_escalation')
    op.drop_table('alert_escalation')
    op.drop_index('ix_pm_outcome', table_name='post_mortem', schema='alert')
    op.drop_table('post_mortem', schema='alert')
    op.drop_index('ix_analog_alert', table_name='historical_analog', schema='alert')
    op.drop_table('historical_analog', schema='alert')
    op.drop_index('ix_evidence_alert', table_name='evidence_chain', schema='alert')
    op.drop_table('evidence_chain', schema='alert')
    op.drop_index('ix_feedback_alert', table_name='analyst_feedback', schema='alert')
    op.drop_table('analyst_feedback', schema='alert')
    op.drop_index('ix_alert_rule_trigger_rule_triggered', table_name='alert_rule_trigger', schema='alert')
    op.drop_index('ix_alert_rule_trigger_cooldown', table_name='alert_rule_trigger', schema='alert')
    op.drop_table('alert_rule_trigger', schema='alert')
    op.drop_index('ix_alert_status', table_name='alert', schema='alert')
    op.drop_index('ix_alert_severity', table_name='alert', schema='alert')
    op.drop_index('ix_alert_created', table_name='alert', schema='alert')
    op.drop_table('alert', schema='alert')
    op.drop_index('ix_anomaly_flag', table_name='anomaly_result', schema='signal')
    op.drop_index('ix_anomaly_ensemble', table_name='anomaly_result', schema='signal')
    op.drop_table('anomaly_result', schema='signal')
    op.drop_index('ix_norm_source_time', table_name='normalized_event', schema='ingestion')
    op.drop_index('ix_norm_entity_value', table_name='normalized_event', schema='ingestion')
    op.drop_index('ix_norm_entity_time', table_name='normalized_event', schema='ingestion')
    op.drop_table('normalized_event', schema='ingestion')
    op.drop_index(op.f('ix_trend_time_series_timestamp'), table_name='trend_time_series')
    op.drop_index(op.f('ix_trend_time_series_keyword_id'), table_name='trend_time_series')
    op.drop_index(op.f('ix_trend_time_series_geo'), table_name='trend_time_series')
    op.drop_index('idx_trend_time_series_keyword_timestamp', table_name='trend_time_series')
    op.drop_index('idx_trend_time_series_geo_timestamp', table_name='trend_time_series')
    op.drop_table('trend_time_series')
    op.drop_index(op.f('ix_trend_alerts_keyword_id'), table_name='trend_alerts')
    op.drop_index(op.f('ix_trend_alerts_geo'), table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_type_triggered', table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_severity', table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_keyword_triggered', table_name='trend_alerts')
    op.drop_table('trend_alerts')
    op.drop_index('ix_signal_source_bucket', table_name='signal_time_series', schema='signal')
    op.drop_index('ix_signal_entity_time', table_name='signal_time_series', schema='signal')
    op.drop_table('signal_time_series', schema='signal')
    op.drop_table('semantic_cluster_member', schema='signal')
    op.drop_index('ix_raw_source_time', table_name='raw_ingestion', schema='ingestion')
    op.drop_table('raw_ingestion', schema='ingestion')
    op.drop_index('ix_alert_rule_analytics_rule_id', table_name='alert_rule_analytics', schema='alert')
    op.drop_index('ix_alert_rule_analytics_period', table_name='alert_rule_analytics', schema='alert')
    op.drop_table('alert_rule_analytics', schema='alert')
    op.drop_index(op.f('ix_trend_snapshots_geo'), table_name='trend_snapshots')
    op.drop_index('idx_trend_snapshots_geo_captured', table_name='trend_snapshots')
    op.drop_index('idx_trend_snapshots_captured', table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_trend_keywords_keyword'), table_name='trend_keywords')
    op.drop_index(op.f('ix_trend_keywords_geo'), table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_last_seen', table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_keyword_geo', table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_category', table_name='trend_keywords')
    op.drop_table('trend_keywords')
    op.drop_index('ix_cluster_drift', table_name='semantic_cluster', schema='signal')
    op.drop_table('semantic_cluster', schema='signal')
    op.drop_table('scheduled_reports')
    op.drop_table('report_templates')
    op.drop_table('source_registry', schema='ingestion')
    op.drop_index('ix_backtest_status', table_name='backtest_run', schema='backtest')
    op.drop_table('backtest_run', schema='backtest')
    op.drop_index('ix_alert_template_name', table_name='alert_template')
    op.drop_index('ix_alert_template_is_default', table_name='alert_template')
    op.drop_table('alert_template')
    op.drop_index('ix_user_username', table_name='user', schema='alert')
    op.drop_index('ix_user_email', table_name='user', schema='alert')
    op.drop_table('user', schema='alert')
    # ### end Alembic commands ###
