"""add market data table

Revision ID: 8dfa97a8efc0
Revises: 8f229f7d1ade
Create Date: 2026-02-10 05:30:48.844099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dfa97a8efc0'
down_revision: Union[str, None] = '8f229f7d1ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable name for the rule'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this rule detects'),
    sa.Column('condition_type', sa.String(length=50), nullable=False, comment='Type of condition: velocity_threshold, rank_change, interest_spike, correlation, etc.'),
    sa.Column('threshold_value', sa.Float(), nullable=False, comment='Threshold value for the condition'),
    sa.Column('comparison_operator', sa.String(length=10), nullable=False, comment='Comparison operator: >, <, >=, <=, =='),
    sa.Column('target_keywords', postgresql.ARRAY(sa.String()), nullable=True, comment='Specific keywords to monitor (empty = all keywords)'),
    sa.Column('target_categories', postgresql.ARRAY(sa.String()), nullable=True, comment='Categories to monitor (empty = all categories)'),
    sa.Column('geo_scope', postgresql.ARRAY(sa.String()), nullable=True, comment='Geographic regions to monitor (empty = all regions)'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False, comment='Default severity for alerts created by this rule'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this rule is active'),
    sa.Column('notify_email', sa.Boolean(), nullable=False, comment='Send email notifications for alerts from this rule'),
    sa.Column('notify_desktop', sa.Boolean(), nullable=False, comment='Send desktop notifications for alerts from this rule'),
    sa.Column('email_recipients', postgresql.ARRAY(sa.String()), nullable=True, comment='Email addresses to notify'),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False, comment='Minimum time between alerts for the same entity'),
    sa.Column('rule_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional rule configuration (time windows, patterns, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='User-defined rules for alert generation'
    )
    op.create_index('ix_alert_rule_condition_type', 'alert_rule', ['condition_type'], unique=False, schema='alert')
    op.create_index('ix_alert_rule_enabled', 'alert_rule', ['enabled'], unique=False, schema='alert')
    op.create_table('replay_session',
    sa.Column('user_id', sa.String(length=256), nullable=False, comment='User who created this replay session'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Descriptive name for the replay session'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of replay purpose'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Start of replay time window'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='End of replay time window'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Replay parameters: confidence_thresholds, detector_weights, etc.'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: created, running, completed, failed'),
    sa.Column('progress_percentage', sa.Float(), nullable=True, comment='Progress through the replay (0.0-1.0)'),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Number of alerts that would have been generated'),
    sa.Column('trades_simulated', sa.Integer(), nullable=False, comment='Number of trades that would have been executed'),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Key insights from the replay analysis'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Replay sessions for post-mortem analysis'
    )
    op.create_index('ix_replay_status', 'replay_session', ['status'], unique=False, schema='alert')
    op.create_index('ix_replay_time_range', 'replay_session', ['start_time', 'end_time'], unique=False, schema='alert')
    op.create_index('ix_replay_user', 'replay_session', ['user_id'], unique=False, schema='alert')
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False, comment='Login username (unique, case-insensitive enforced at app level)'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Email address for notifications and password recovery'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='bcrypt-hashed password (never store plaintext)'),
    sa.Column('display_name', sa.String(length=256), nullable=False, comment='Human-readable display name'),
    sa.Column('role', sa.String(length=32), server_default='analyst', nullable=False, comment='Authorization role: admin | analyst | viewer'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag — inactive users cannot log in'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='alert'
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True, schema='alert')
    op.create_index('ix_user_username', 'user', ['username'], unique=True, schema='alert')
    op.create_table('alert_template',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable name for the template'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of when to use this template'),
    sa.Column('subject_template', sa.String(length=255), nullable=False, comment='Jinja2 template for email subject line'),
    sa.Column('html_template', sa.Text(), nullable=False, comment='Jinja2 template for HTML email body'),
    sa.Column('text_template', sa.Text(), nullable=False, comment='Jinja2 template for plain text email body'),
    sa.Column('severity_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Severities this template applies to (empty = all severities)'),
    sa.Column('category_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Categories this template applies to (empty = all categories)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default template for matching alerts'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Whether this is a system template (cannot be deleted)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this template is active'),
    sa.Column('template_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional template configuration (CSS, images, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    comment='Customizable alert notification templates'
    )
    op.create_index('ix_alert_template_is_default', 'alert_template', ['is_default'], unique=False)
    op.create_index('ix_alert_template_name', 'alert_template', ['name'], unique=False)
    op.create_table('backtest_run',
    sa.Column('name', sa.String(length=256), nullable=False, comment="Human-readable name, e.g. '2023 Banking Stress replay'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='Historical replay starts here'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='Historical replay ends here'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full parameter snapshot (thresholds, weights, etc.)'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus'), nullable=False, comment='pending → running → completed / failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Total alerts produced during replay'),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('missed_events', sa.Integer(), nullable=False, comment='Known real events that were NOT flagged'),
    sa.Column('results_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extended metrics: precision, recall, F1, lead-time dist'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    schema='backtest',
    comment='Synthetic backtest execution records'
    )
    op.create_index('ix_backtest_status', 'backtest_run', ['status'], unique=False, schema='backtest')
    op.create_table('source_registry',
    sa.Column('name', sa.String(length=128), nullable=False, comment="Human-readable source name, e.g. 'google_trends'"),
    sa.Column('source_type', sa.Enum('SEARCH', 'WIKI', 'SOCIAL', 'NEWS', 'FINANCE', 'HEALTH', 'ALT_DATA', name='sourcetype'), nullable=False, comment='Broad category: search / wiki / social / news / …'),
    sa.Column('description', sa.Text(), nullable=True, comment='Free-text notes about the source'),
    sa.Column('api_endpoint', sa.String(length=1024), nullable=True, comment='Base URL or ARN of the external API'),
    sa.Column('auth_method', sa.String(length=64), nullable=True, comment='oauth2 | api_key | iam_role | none'),
    sa.Column('update_frequency_seconds', sa.Integer(), nullable=False, comment='How often (seconds) the connector runs'),
    sa.Column('data_latency_seconds', sa.Integer(), nullable=False, comment='Typical delay between real-world event and availability'),
    sa.Column('health_status', sa.Enum('LIVE', 'DEGRADED', 'DOWN', name='healthstatus'), nullable=False, comment='Current operational state: live / degraded / down'),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful data pull'),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False, comment='Rolling failure count; resets on success'),
    sa.Column('default_weight', sa.Float(), nullable=False, comment='Baseline weight used in ensemble confidence scoring'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Master on/off switch for this connector'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_source_name'),
    schema='ingestion',
    comment='Catalogue of all data sources'
    )
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for market data entry'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Stock symbol (e.g., AAPL, GOOGL)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of the data point'),
    sa.Column('data_type', sa.String(length=20), nullable=False, comment='Type of data: bar, quote, trade'),
    sa.Column('open_price', sa.Float(), nullable=True, comment='Opening price for bar data'),
    sa.Column('high_price', sa.Float(), nullable=True, comment='High price for bar data'),
    sa.Column('low_price', sa.Float(), nullable=True, comment='Low price for bar data'),
    sa.Column('close_price', sa.Float(), nullable=True, comment='Closing price for bar data'),
    sa.Column('volume', sa.Integer(), nullable=True, comment='Trading volume'),
    sa.Column('bid_price', sa.Float(), nullable=True, comment='Bid price for quote data'),
    sa.Column('ask_price', sa.Float(), nullable=True, comment='Ask price for quote data'),
    sa.Column('bid_size', sa.Integer(), nullable=True, comment='Bid size'),
    sa.Column('ask_size', sa.Integer(), nullable=True, comment='Ask size'),
    sa.Column('trade_price', sa.Float(), nullable=True, comment='Trade price'),
    sa.Column('trade_size', sa.Integer(), nullable=True, comment='Trade size'),
    sa.Column('source', sa.String(length=50), server_default='alpaca', nullable=False, comment='Data source (alpaca, yahoo, etc.)'),
    sa.Column('timeframe', sa.String(length=20), nullable=True, comment='Timeframe for bar data (1Min, 5Min, etc.)'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Raw data from source for debugging'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_symbol', 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_timestamp', 'market_data', ['symbol', 'timestamp'], unique=False)
    op.create_index('ix_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_table('narrative_clusters',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('representative_title', sa.Text(), nullable=False),
    sa.Column('source_distribution', sa.JSON(), nullable=False),
    sa.Column('average_tone', sa.Float(), nullable=False),
    sa.Column('coverage_intensity', sa.Float(), nullable=False),
    sa.Column('time_span_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('email_subject_template', sa.String(length=255), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_time', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('email_recipients', sa.JSON(), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_cluster',
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the observation window'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='End of the observation window'),
    sa.Column('label', sa.String(length=256), nullable=True, comment='Auto-generated or analyst-assigned cluster label'),
    sa.Column('centroid_vector', postgresql.ARRAY(Float()), nullable=False, comment='Mean SBERT embedding vector (768-d or 384-d)'),
    sa.Column('cluster_size', sa.Integer(), nullable=False, comment='Number of unique entities in this cluster'),
    sa.Column('drift_score', sa.Float(), nullable=False, comment='Cosine distance the centroid moved since the prior window'),
    sa.Column('drift_flag', sa.Boolean(), nullable=False, comment='True when drift exceeds threshold (rapid semantic shift)'),
    sa.Column('prior_cluster_id', sa.UUID(), nullable=True, comment='The same logical cluster from the previous time window'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['prior_cluster_id'], ['signal.semantic_cluster.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='signal',
    comment='SBERT topic clusters with drift tracking'
    )
    op.create_index('ix_cluster_drift', 'semantic_cluster', ['drift_score'], unique=False, schema='signal')
    op.create_table('trend_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('current_rank', sa.Integer(), nullable=True),
    sa.Column('current_traffic', sa.String(length=50), nullable=True),
    sa.Column('current_traffic_value', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peak_rank', sa.Integer(), nullable=True),
    sa.Column('total_appearances', sa.Integer(), nullable=False),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('velocity_trend', sa.JSON(), nullable=True),
    sa.Column('direction_changes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_keywords_category', 'trend_keywords', ['category'], unique=False)
    op.create_index('idx_trend_keywords_keyword_geo', 'trend_keywords', ['keyword', 'geo'], unique=False)
    op.create_index('idx_trend_keywords_last_seen', 'trend_keywords', ['last_seen'], unique=False)
    op.create_index(op.f('ix_trend_keywords_geo'), 'trend_keywords', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_keywords_keyword'), 'trend_keywords', ['keyword'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_trends', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('trends_data', sa.JSON(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('rate_limited', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_snapshots_captured', 'trend_snapshots', ['captured_at'], unique=False)
    op.create_index('idx_trend_snapshots_geo_captured', 'trend_snapshots', ['geo', 'captured_at'], unique=False)
    op.create_index(op.f('ix_trend_snapshots_geo'), 'trend_snapshots', ['geo'], unique=False)
    op.create_table('alert_rule_analytics',
    sa.Column('rule_id', sa.UUID(), nullable=False, comment='The alert rule being analyzed'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the analytics period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of the analytics period'),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Total alerts generated by this rule in the period'),
    sa.Column('alerts_confirmed', sa.Integer(), nullable=False, comment='Alerts confirmed as true positives'),
    sa.Column('alerts_dismissed', sa.Integer(), nullable=False, comment='Alerts dismissed as false positives'),
    sa.Column('alerts_escalated', sa.Integer(), nullable=False, comment='Alerts that were escalated'),
    sa.Column('average_response_time_minutes', sa.Float(), nullable=True, comment='Average time from alert creation to resolution (minutes)'),
    sa.Column('precision_score', sa.Float(), nullable=True, comment='Precision: confirmed / (confirmed + dismissed)'),
    sa.Column('recall_score', sa.Float(), nullable=True, comment='Recall: confirmed / total relevant events (if available)'),
    sa.Column('effectiveness_score', sa.Float(), nullable=True, comment='Overall effectiveness score (0-1)'),
    sa.Column('false_positive_rate', sa.Float(), nullable=True, comment='False positive rate: dismissed / total alerts'),
    sa.Column('alert_volume_trend', sa.Float(), nullable=True, comment='Trend in alert volume (+/- percentage change)'),
    sa.Column('analytics_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional analytics data (severity distribution, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert.alert_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Performance analytics for alert rules'
    )
    op.create_index('ix_alert_rule_analytics_period', 'alert_rule_analytics', ['period_start', 'period_end'], unique=False, schema='alert')
    op.create_index('ix_alert_rule_analytics_rule_id', 'alert_rule_analytics', ['rule_id'], unique=False, schema='alert')
    op.create_table('replay_signal',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The entity this signal is about'),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False, comment='When this signal occurred'),
    sa.Column('original_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Original anomaly scores from detectors'),
    sa.Column('adjusted_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Scores after applying replay parameters'),
    sa.Column('would_trigger_alert', sa.Boolean(), nullable=False, comment='Whether this signal would trigger an alert with current parameters'),
    sa.Column('confidence_level', sa.Float(), nullable=False, comment='Final confidence score (0.0-1.0)'),
    sa.Column('signal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional signal metadata (source, trend data, etc.)'),
    sa.Column('parameter_sensitivity', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='How sensitive this signal is to parameter changes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Signals processed during replay sessions'
    )
    op.create_index('ix_replay_signal_entity', 'replay_signal', ['entity_value'], unique=False, schema='alert')
    op.create_index('ix_replay_signal_session', 'replay_signal', ['session_id'], unique=False, schema='alert')
    op.create_index('ix_replay_signal_time', 'replay_signal', ['signal_time'], unique=False, schema='alert')
    op.create_table('replay_snapshot',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False, comment='Point in time this snapshot represents'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Sequential order within the replay session'),
    sa.Column('active_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Active signals at this point: [{'entity': str, 'score': float, ...}]"),
    sa.Column('system_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='System parameters at this time (thresholds, weights, etc.)'),
    sa.Column('market_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Market conditions snapshot (volatility, trends, etc.)'),
    sa.Column('portfolio_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Portfolio state: positions, cash, P&L, etc.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='System state snapshots during replay'
    )
    op.create_index('ix_snapshot_session_time', 'replay_snapshot', ['session_id', 'snapshot_time'], unique=False, schema='alert')
    op.create_table('raw_ingestion',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Which source produced this payload'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When VanguardSignal received this data'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete API response body stored as JSONB'),
    sa.Column('payload_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw payload bytes'),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False, comment='Byte length of the original payload'),
    sa.Column('schema_version', sa.String(length=32), nullable=False, comment='Version tag for the upstream API schema'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='False if schema validation failed at ingest'),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured list of validation failures, if any'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion',
    comment='Immutable raw API payloads'
    )
    op.create_index('ix_raw_source_time', 'raw_ingestion', ['source_id', 'ingested_at'], unique=False, schema='ingestion')
    op.create_table('narrative_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('saturation_score', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['narrative_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_saturation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('saturation_score', sa.Float(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=20), nullable=False),
    sa.Column('coverage_volume', sa.Integer(), nullable=False),
    sa.Column('source_concentration', sa.Float(), nullable=False),
    sa.Column('repetition_score', sa.Float(), nullable=False),
    sa.Column('temporal_distribution', sa.Float(), nullable=False),
    sa.Column('is_saturated', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['narrative_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_data_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_data_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('model_parameters', sa.JSON(), nullable=False),
    sa.Column('training_mae', sa.Float(), nullable=True),
    sa.Column('training_rmse', sa.Float(), nullable=True),
    sa.Column('training_mape', sa.Float(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('last_prediction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('retrain_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prediction_models_keyword_active', 'prediction_models', ['keyword_id', 'is_active'], unique=False)
    op.create_index('idx_prediction_models_type_version', 'prediction_models', ['model_type', 'model_version'], unique=False)
    op.create_index(op.f('ix_prediction_models_keyword_id'), 'prediction_models', ['keyword_id'], unique=False)
    op.create_table('semantic_cluster_member',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The search term, page title, etc.'),
    sa.Column('embedding_vector', postgresql.ARRAY(Float()), nullable=True, comment="This entity's individual SBERT embedding"),
    sa.Column('distance_to_centroid', sa.Float(), nullable=False, comment='Cosine distance from entity embedding to cluster centroid'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['cluster_id'], ['signal.semantic_cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'entity_value', name='uq_cluster_entity'),
    schema='signal',
    comment='Entity membership in semantic clusters'
    )
    op.create_table('signal_time_series',
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='Search term, page title, etc.'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Which source produced this series'),
    sa.Column('bucket_size', sa.Enum('HOUR', 'DAY', 'WEEK', 'MONTH', name='timebucket'), nullable=False, comment='Aggregation granularity: hour / day / week / month'),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False, comment='Inclusive start of this time bucket'),
    sa.Column('bucket_end', sa.DateTime(timezone=True), nullable=False, comment='Exclusive end of this time bucket'),
    sa.Column('value', sa.Float(), nullable=False, comment='Aggregated metric (mean interest, total views, …)'),
    sa.Column('sample_count', sa.Integer(), nullable=False, comment='Number of NormalizedEvents that were aggregated'),
    sa.Column('coverage_score', sa.Float(), nullable=False, comment='1.0 = full data; <1.0 = degraded coverage'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_value', 'source_id', 'bucket_size', 'bucket_start', name='uq_signal_entity_bucket'),
    schema='signal',
    comment='Aggregated time-series per entity'
    )
    op.create_index('ix_signal_entity_time', 'signal_time_series', ['entity_value', 'bucket_start'], unique=False, schema='signal')
    op.create_index('ix_signal_source_bucket', 'signal_time_series', ['source_id', 'bucket_start'], unique=False, schema='signal')
    op.create_table('portfolio',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who owns this portfolio'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Portfolio display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Portfolio description'),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False, comment='Portfolio base currency (ISO 4217)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Active portfolio flag'),
    sa.Column('is_paper_trading', sa.Boolean(), server_default='true', nullable=False, comment='Paper trading mode (no real money)'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False, comment='Available cash balance'),
    sa.Column('total_value', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False, comment='Total portfolio value (cash + positions)'),
    sa.Column('max_position_size', sa.Numeric(precision=10, scale=4), nullable=True, comment='Maximum position size as % of portfolio (0.01 = 1%)'),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=4), nullable=True, comment='Maximum daily loss as % of portfolio (0.02 = 2%)'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True, comment='Maximum drawdown limit as % of portfolio'),
    sa.Column('allow_margin', sa.Boolean(), server_default='false', nullable=False, comment='Allow margin trading'),
    sa.Column('allow_short_selling', sa.Boolean(), server_default='false', nullable=False, comment='Allow short selling'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['user_id'], ['alert.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_portfolio_is_active', 'portfolio', ['is_active'], unique=False, schema='trading')
    op.create_index('ix_portfolio_user_id', 'portfolio', ['user_id'], unique=True, schema='trading')
    op.create_table('trend_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rank_at_alert', sa.Integer(), nullable=True),
    sa.Column('interest_at_alert', sa.Float(), nullable=True),
    sa.Column('velocity_at_alert', sa.Float(), nullable=True),
    sa.Column('pct_change_24h', sa.Float(), nullable=True),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('related_news', sa.JSON(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_alerts_keyword_triggered', 'trend_alerts', ['keyword_id', 'triggered_at'], unique=False)
    op.create_index('idx_trend_alerts_severity', 'trend_alerts', ['severity'], unique=False)
    op.create_index('idx_trend_alerts_type_triggered', 'trend_alerts', ['alert_type', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_trend_alerts_geo'), 'trend_alerts', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_alerts_keyword_id'), 'trend_alerts', ['keyword_id'], unique=False)
    op.create_table('trend_time_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interest_score', sa.Float(), nullable=False),
    sa.Column('rank_at_time', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['trend_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_time_series_geo_timestamp', 'trend_time_series', ['geo', 'timestamp'], unique=False)
    op.create_index('idx_trend_time_series_keyword_timestamp', 'trend_time_series', ['keyword_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trend_time_series_geo'), 'trend_time_series', ['geo'], unique=False)
    op.create_index(op.f('ix_trend_time_series_keyword_id'), 'trend_time_series', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_trend_time_series_timestamp'), 'trend_time_series', ['timestamp'], unique=False)
    op.create_table('news_articles',
    sa.Column('title', sa.String(length=512), nullable=False, comment='Article headline or title'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Article summary or excerpt'),
    sa.Column('url', sa.String(length=2048), nullable=True, comment='Original article URL'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Source that provided this article'),
    sa.Column('raw_id', sa.UUID(), nullable=True, comment='Link to raw ingestion record if available'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='When the article was published'),
    sa.Column('author', sa.String(length=256), nullable=True, comment='Article author if available'),
    sa.Column('language', sa.String(length=8), nullable=True, comment='ISO 639-1 language code'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Sentiment analysis score (-1 to 1)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['raw_id'], ['ingestion.raw_ingestion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion',
    comment='Structured news articles for analysis'
    )
    op.create_index('ix_news_published', 'news_articles', ['published_at'], unique=False, schema='ingestion')
    op.create_index('ix_news_source', 'news_articles', ['source_id'], unique=False, schema='ingestion')
    op.create_table('normalized_event',
    sa.Column('raw_id', sa.UUID(), nullable=False, comment='Link back to the immutable raw payload (audit trail)'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Denormalized source FK for fast filtering'),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False, comment='When the event actually occurred (source timestamp)'),
    sa.Column('entity_type', sa.Enum('SEARCH_QUERY', 'WIKI_PAGE', 'SOCIAL_POST', 'NEWS_HEADLINE', 'FINANCIAL_TICK', 'HEALTH_REPORT', name='entitytype'), nullable=False, comment='Kind of entity: search_query / wiki_page / …'),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The search term, page title, headline text, etc.'),
    sa.Column('metric_value', sa.Float(), nullable=False, comment='Numeric measure: search interest, page views, sentiment, …'),
    sa.Column('geo', sa.String(length=8), nullable=True, comment='ISO 3166-1 alpha-2 country code, if available'),
    sa.Column('language', sa.String(length=8), nullable=True, comment='ISO 639-1 language code, if available'),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Catch-all for source-specific fields not in the schema'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['raw_id'], ['ingestion.raw_ingestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion.source_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion',
    comment='Cleaned, schema-conformant events'
    )
    op.create_index('ix_norm_entity_time', 'normalized_event', ['entity_type', 'event_time'], unique=False, schema='ingestion')
    op.create_index('ix_norm_entity_value', 'normalized_event', ['entity_value'], unique=False, schema='ingestion')
    op.create_index('ix_norm_source_time', 'normalized_event', ['source_id', 'event_time'], unique=False, schema='ingestion')
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('actual_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('prediction_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['prediction_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prediction_results_horizon', 'prediction_results', ['horizon_hours'], unique=False)
    op.create_index('idx_prediction_results_model_timestamp', 'prediction_results', ['model_id', 'prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_prediction_results_model_id'), 'prediction_results', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_results_prediction_timestamp'), 'prediction_results', ['prediction_timestamp'], unique=False)
    op.create_table('anomaly_result',
    sa.Column('series_id', sa.UUID(), nullable=False, comment='The time-series bucket that was evaluated'),
    sa.Column('detection_time', sa.DateTime(timezone=True), nullable=False, comment='When this detection pass ran'),
    sa.Column('stl_trend', sa.Float(), nullable=True, comment='Trend component from STL decomposition'),
    sa.Column('stl_seasonal', sa.Float(), nullable=True, comment='Seasonal component from STL decomposition'),
    sa.Column('stl_residual', sa.Float(), nullable=True, comment='Residual after removing trend + seasonality'),
    sa.Column('stl_residual_zscore', sa.Float(), nullable=True, comment='Z-score of the residual (how many σ from mean)'),
    sa.Column('iforest_score', sa.Float(), nullable=True, comment='Isolation Forest anomaly score (−1 to 0 range typical)'),
    sa.Column('iforest_contamination', sa.Float(), nullable=True, comment='Contamination parameter used for this run'),
    sa.Column('cusum_score', sa.Float(), nullable=True, comment='CUSUM statistic; large values → sustained mean shift'),
    sa.Column('cusum_threshold', sa.Float(), nullable=True, comment='The threshold that was in effect for CUSUM'),
    sa.Column('cusum_drift', sa.Float(), nullable=True, comment='Allowable drift parameter used for this run'),
    sa.Column('velocity_score', sa.Float(), nullable=True, comment='Velocity detector normalised score (0–1); high = rapid acceleration'),
    sa.Column('velocity_acceleration', sa.Float(), nullable=True, comment='Raw second derivative (acceleration) at the latest point'),
    sa.Column('weight_stl', sa.Float(), nullable=False, comment='Weight assigned to STL Z-score in the ensemble'),
    sa.Column('weight_iforest', sa.Float(), nullable=False, comment='Weight assigned to Isolation Forest score'),
    sa.Column('weight_cusum', sa.Float(), nullable=False, comment='Weight assigned to CUSUM score'),
    sa.Column('weight_velocity', sa.Float(), nullable=False, comment='Weight assigned to Velocity detector score'),
    sa.Column('ensemble_score', sa.Float(), nullable=False, comment='Final combined anomaly score'),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False, comment='True when ensemble_score exceeds alert threshold'),
    sa.Column('ensemble_threshold', sa.Float(), nullable=False, comment='The threshold that was in effect for this decision'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['series_id'], ['signal.signal_time_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'detection_time', name='uq_anomaly_series_time'),
    schema='signal',
    comment='Per-bucket ensemble anomaly scores'
    )
    op.create_index('ix_anomaly_ensemble', 'anomaly_result', ['ensemble_score'], unique=False, schema='signal')
    op.create_index('ix_anomaly_flag', 'anomaly_result', ['is_anomaly'], unique=False, schema='signal')
    op.create_table('order',
    sa.Column('portfolio_id', sa.UUID(), nullable=False, comment='Portfolio this order belongs to'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol/ticker'),
    sa.Column('side', sa.String(length=4), nullable=False, comment='Order side: buy | sell'),
    sa.Column('order_type', sa.String(length=10), nullable=False, comment='Order type: market | limit | stop'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='Order quantity'),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Limit price (for limit/stop orders)'),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Stop price (for stop orders)'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='Order status: pending | filled | partial | cancelled | rejected'),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False, comment='Quantity that has been filled'),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Average price of filled portions'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='When order was submitted'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True, comment='When order was completely filled'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='When order was cancelled'),
    sa.Column('external_order_id', sa.String(length=256), nullable=True, comment='Broker/external order identifier'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Order notes or comments'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['trading.portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_order_created_at', 'order', ['created_at'], unique=False, schema='trading')
    op.create_index('ix_order_portfolio_id', 'order', ['portfolio_id'], unique=False, schema='trading')
    op.create_index('ix_order_status', 'order', ['status'], unique=False, schema='trading')
    op.create_index('ix_order_symbol', 'order', ['symbol'], unique=False, schema='trading')
    op.create_table('position',
    sa.Column('portfolio_id', sa.UUID(), nullable=False, comment='Portfolio this position belongs to'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol/ticker'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='Current position quantity (positive = long, negative = short)'),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=8), nullable=False, comment='Average cost basis per unit'),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Current market price'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=8), nullable=True, comment='Current market value (quantity * current_price)'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False, comment='Unrealized profit/loss'),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False, comment='Realized profit/loss from closed portions'),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='When position was first opened'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last position update timestamp'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['trading.portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_position_portfolio_id', 'position', ['portfolio_id'], unique=False, schema='trading')
    op.create_index('ix_position_portfolio_symbol', 'position', ['portfolio_id', 'symbol'], unique=True, schema='trading')
    op.create_index('ix_position_symbol', 'position', ['symbol'], unique=False, schema='trading')
    op.create_table('risk_metrics',
    sa.Column('portfolio_id', sa.UUID(), nullable=False, comment='Portfolio these metrics belong to'),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='When these metrics were calculated'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='Sharpe ratio (risk-adjusted returns)'),
    sa.Column('sortino_ratio', sa.Float(), nullable=True, comment='Sortino ratio (downside risk only)'),
    sa.Column('max_drawdown', sa.Float(), nullable=True, comment='Maximum drawdown percentage'),
    sa.Column('value_at_risk', sa.Float(), nullable=True, comment='Value at Risk (95% confidence)'),
    sa.Column('expected_shortfall', sa.Float(), nullable=True, comment='Expected shortfall (CVaR)'),
    sa.Column('volatility', sa.Float(), nullable=True, comment='Portfolio volatility (annualized)'),
    sa.Column('beta', sa.Float(), nullable=True, comment='Portfolio beta vs market'),
    sa.Column('largest_position_pct', sa.Float(), nullable=True, comment='Largest position as % of portfolio'),
    sa.Column('top_10_positions_pct', sa.Float(), nullable=True, comment='Top 10 positions as % of portfolio'),
    sa.Column('daily_turnover', sa.Float(), nullable=True, comment='Daily turnover rate'),
    sa.Column('win_rate', sa.Float(), nullable=True, comment='Percentage of winning trades'),
    sa.Column('profit_factor', sa.Float(), nullable=True, comment='Gross profit / gross loss ratio'),
    sa.Column('risk_warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='JSON object with risk warning flags'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['trading.portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_risk_metrics_portfolio_date', 'risk_metrics', ['portfolio_id', 'calculated_at'], unique=False, schema='trading')
    op.create_index('ix_risk_metrics_portfolio_id', 'risk_metrics', ['portfolio_id'], unique=False, schema='trading')
    op.create_table('alert',
    sa.Column('primary_entity', sa.String(length=1024), nullable=False, comment='The entity (search term, page, …) at the center of the anomaly'),
    sa.Column('related_entities', postgresql.ARRAY(String()), nullable=True, comment='Other entities co-occurring in the same anomaly window'),
    sa.Column('anomaly_result_id', sa.UUID(), nullable=True, comment='The specific anomaly row that spawned this alert'),
    sa.Column('trigger_rule_id', sa.UUID(), nullable=True, comment='The alert rule that triggered this alert (if rule-based)'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False, comment='low / medium / high / critical'),
    sa.Column('status', sa.Enum('ACTIVE', 'WATCHING', 'CONFIRMED', 'DISMISSED', 'RESOLVED', 'ARCHIVED', name='alertstatus'), nullable=False, comment='Lifecycle: active → watching → confirmed/dismissed → resolved'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Final confidence (0.0 – 1.0)'),
    sa.Column('ensemble_anomaly_score', sa.Float(), nullable=False, comment="Anomaly engine's ensemble output"),
    sa.Column('source_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Per-source weight snapshot, e.g. {"google_trends": 0.6, "wikipedia": 0.4}'),
    sa.Column('semantic_drift_score', sa.Float(), nullable=False, comment='Semantic drift contribution (0.0 until Phase 2)'),
    sa.Column('reason_code', sa.String(length=128), nullable=False, comment='Machine-readable reason, e.g. CUSUM_SHIFT, STL_SPIKE, DRIFT'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='Auto-generated plain-English explanation for the analyst'),
    sa.Column('signal_start', sa.DateTime(timezone=True), nullable=False, comment='Earliest timestamp of the contributing anomaly window'),
    sa.Column('signal_end', sa.DateTime(timezone=True), nullable=False, comment='Latest timestamp of the contributing anomaly window'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['anomaly_result_id'], ['signal.anomaly_result.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['alert.alert_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Flagged anomalies for analyst review'
    )
    op.create_index('ix_alert_created', 'alert', ['created_at'], unique=False, schema='alert')
    op.create_index('ix_alert_severity', 'alert', ['severity'], unique=False, schema='alert')
    op.create_index('ix_alert_status', 'alert', ['status'], unique=False, schema='alert')
    op.create_table('narrative_cluster_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['ingestion.news_articles.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['narrative_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rule_trigger',
    sa.Column('rule_id', sa.UUID(), nullable=False, comment='The rule that was triggered'),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The entity (keyword, term) that triggered the rule'),
    sa.Column('geo', sa.String(length=5), nullable=False, comment='Geographic region where trigger occurred'),
    sa.Column('actual_value', sa.Float(), nullable=False, comment='The actual measured value that triggered the rule'),
    sa.Column('threshold_value', sa.Float(), nullable=False, comment='The threshold value that was exceeded'),
    sa.Column('alert_created', sa.Boolean(), nullable=False, comment='Whether an alert was actually created from this trigger'),
    sa.Column('alert_id', sa.UUID(), nullable=True, comment='The alert that was created (if any)'),
    sa.Column('trigger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context about the trigger (time series data, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert.alert_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Tracks alert rule trigger history'
    )
    op.create_index('ix_alert_rule_trigger_cooldown', 'alert_rule_trigger', ['rule_id', 'entity_value', 'geo'], unique=False, schema='alert')
    op.create_index('ix_alert_rule_trigger_rule_triggered', 'alert_rule_trigger', ['rule_id', 'created_at'], unique=False, schema='alert')
    op.create_table('analyst_feedback',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False, comment="Analyst's identity (from auth provider)"),
    sa.Column('verdict', sa.Enum('CONFIRM', 'DISMISS', name='feedbackverdict'), nullable=False, comment='confirm or dismiss'),
    sa.Column('confidence', sa.Float(), nullable=True, comment="Analyst's self-reported confidence in the verdict (0–1)"),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional free-text reasoning'),
    sa.Column('was_used_for_training', sa.Boolean(), nullable=False, comment='True once the RL training loop has consumed this row'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Analyst confirm/dismiss verdicts'
    )
    op.create_index('ix_feedback_alert', 'analyst_feedback', ['alert_id'], unique=False, schema='alert')
    op.create_table('evidence_chain',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('raw_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of RawIngestion rows that contributed'),
    sa.Column('normalized_event_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of NormalizedEvent rows'),
    sa.Column('series_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of SignalTimeSeries rows'),
    sa.Column('anomaly_ids', postgresql.ARRAY(String()), nullable=False, comment='UUIDs of AnomalyResult rows'),
    sa.Column('explainability_text', sa.Text(), nullable=False, comment='Auto-generated narrative explaining how evidence connects'),
    sa.Column('evidence_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional structured data for the evidence visualization'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Audit trail linking alerts to raw data'
    )
    op.create_index('ix_evidence_alert', 'evidence_chain', ['alert_id'], unique=False, schema='alert')
    op.create_table('historical_analog',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='The NEW alert we are providing context for'),
    sa.Column('matched_alert_id', sa.UUID(), nullable=False, comment='The HISTORICAL alert that looks similar'),
    sa.Column('similarity_score', sa.Float(), nullable=False, comment='0.0 (no match) – 1.0 (identical pattern)'),
    sa.Column('similarity_method', sa.String(length=64), nullable=False, comment='Algorithm used: dtw_cosine / euclidean / …'),
    sa.Column('reference_period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the historical reference window'),
    sa.Column('reference_period_end', sa.DateTime(timezone=True), nullable=False, comment='End of the historical reference window'),
    sa.Column('analog_summary', sa.Text(), nullable=True, comment='Plain-English description of the historical event'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Similar historical patterns for context'
    )
    op.create_index('ix_analog_alert', 'historical_analog', ['alert_id'], unique=False, schema='alert')
    op.create_table('post_mortem',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='One post-mortem per alert'),
    sa.Column('event_outcome', sa.Enum('TRUE_POSITIVE', 'FALSE_POSITIVE', 'INCONCLUSIVE', name='eventoutcome'), nullable=False, comment='true_positive / false_positive / inconclusive'),
    sa.Column('impact_domain', sa.Enum('FINANCE', 'GEOPOLITICAL', 'HEALTH', 'CIVIL_UNREST', 'CYBER', 'ENVIRONMENTAL', 'OTHER', name='impactdomain'), nullable=True, comment='finance / geopolitical / health / civil_unrest / …'),
    sa.Column('impact_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True, comment='Retrospective severity of the actual event'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Free-text analyst notes on what happened'),
    sa.Column('external_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Links to news articles, government reports, etc.'),
    sa.Column('event_actual_start', sa.DateTime(timezone=True), nullable=True, comment='When the real-world event actually began'),
    sa.Column('event_actual_end', sa.DateTime(timezone=True), nullable=True, comment='When the real-world event resolved'),
    sa.Column('lead_time_hours', sa.Float(), nullable=True, comment='Hours between alert creation and real-world event start'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User or service principal that created the row'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User or service principal that last modified the row'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id'),
    schema='alert',
    comment='Retrospective outcome labels for alerts'
    )
    op.create_index('ix_pm_outcome', 'post_mortem', ['event_outcome'], unique=False, schema='alert')
    op.create_table('replay_decision',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=False, comment='When this decision was made in replay time'),
    sa.Column('decision_type', sa.String(length=32), nullable=False, comment='Type: alert_generated, trade_executed, parameter_changed, etc.'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Sequential order within the replay session'),
    sa.Column('decision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Decision-specific data (alert details, trade parameters, etc.)'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score associated with this decision'),
    sa.Column('original_alert_id', sa.UUID(), nullable=True, comment='Original alert this decision relates to (for comparison)'),
    sa.Column('original_trade_id', sa.UUID(), nullable=True, comment='Original trade this decision relates to (for comparison)'),
    sa.Column('would_have_occurred', sa.Boolean(), nullable=True, comment='Whether this decision would have occurred in reality'),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Analysis of decision impact (P&L, risk, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['original_alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_trade_id'], ['trading.order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert',
    comment='Decisions made during replay sessions'
    )
    op.create_index('ix_decision_session_time', 'replay_decision', ['session_id', 'decision_time'], unique=False, schema='alert')
    op.create_index('ix_decision_type', 'replay_decision', ['decision_type'], unique=False, schema='alert')
    op.create_table('alert_escalation',
    sa.Column('alert_id', sa.UUID(), nullable=False, comment='The alert that was escalated'),
    sa.Column('previous_severity', sa.String(length=20), nullable=False, comment='Severity before escalation (low/medium/high/critical)'),
    sa.Column('new_severity', sa.String(length=20), nullable=False, comment='Severity after escalation (low/medium/high/critical)'),
    sa.Column('escalation_reason', sa.Text(), nullable=True, comment='Human-readable explanation of why escalation occurred'),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False, comment='When the escalation occurred'),
    sa.Column('escalation_trigger', sa.String(length=50), nullable=True, comment="What triggered escalation: 'time_based', 'score_increase', 'repeated'"),
    sa.Column('escalation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context (thresholds, time windows, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks automatic severity escalations for alerts'
    )
    op.create_index('ix_alert_escalation_alert_id', 'alert_escalation', ['alert_id'], unique=False)
    op.create_index('ix_alert_escalation_escalated_at', 'alert_escalation', ['escalated_at'], unique=False)
    op.create_index('ix_alert_escalation_trigger', 'alert_escalation', ['escalation_trigger'], unique=False)
    op.create_table('alert_silence',
    sa.Column('alert_id', sa.UUID(), nullable=True, comment='Specific alert to silence (null for pattern/global silences)'),
    sa.Column('entity_pattern', sa.String(length=1024), nullable=True, comment='Regex pattern to match entity names (for entity-based silencing)'),
    sa.Column('silenced_by', sa.String(length=256), nullable=False, comment='User who created the silence rule'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for silencing'),
    sa.Column('silence_type', sa.String(length=50), nullable=False, comment="Type of silence: 'alert', 'entity', 'global'"),
    sa.Column('silenced_at', sa.DateTime(timezone=True), nullable=False, comment='When the silence was created'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration in minutes (null for indefinite)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the silence expires'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this silence rule is currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks alert silencing/snoozing rules'
    )
    op.create_index('ix_alert_silence_alert_id', 'alert_silence', ['alert_id'], unique=False)
    op.create_index('ix_alert_silence_entity_pattern', 'alert_silence', ['entity_pattern'], unique=False)
    op.create_index('ix_alert_silence_expires_at', 'alert_silence', ['expires_at'], unique=False)
    op.create_index('ix_alert_silence_is_active', 'alert_silence', ['is_active'], unique=False)
    op.create_table('backtest_alert',
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('primary_entity', sa.String(length=1024), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ensemble_anomaly_score', sa.Float(), nullable=False),
    sa.Column('source_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('signal_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_real_alert_id', sa.UUID(), nullable=True, comment='If this backtest alert matches a real historical alert'),
    sa.Column('is_true_positive', sa.Boolean(), nullable=True, comment='Did this correspond to a real event? (from PostMortem)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest.backtest_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_real_alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='backtest',
    comment='Hypothetical alerts from a backtest'
    )
    op.create_index('ix_bt_alert_run', 'backtest_alert', ['backtest_run_id'], unique=False, schema='backtest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bt_alert_run', table_name='backtest_alert', schema='backtest')
    op.drop_table('backtest_alert', schema='backtest')
    op.drop_index('ix_alert_silence_is_active', table_name='alert_silence')
    op.drop_index('ix_alert_silence_expires_at', table_name='alert_silence')
    op.drop_index('ix_alert_silence_entity_pattern', table_name='alert_silence')
    op.drop_index('ix_alert_silence_alert_id', table_name='alert_silence')
    op.drop_table('alert_silence')
    op.drop_index('ix_alert_escalation_trigger', table_name='alert_escalation')
    op.drop_index('ix_alert_escalation_escalated_at', table_name='alert_escalation')
    op.drop_index('ix_alert_escalation_alert_id', table_name='alert_escalation')
    op.drop_table('alert_escalation')
    op.drop_index('ix_decision_type', table_name='replay_decision', schema='alert')
    op.drop_index('ix_decision_session_time', table_name='replay_decision', schema='alert')
    op.drop_table('replay_decision', schema='alert')
    op.drop_index('ix_pm_outcome', table_name='post_mortem', schema='alert')
    op.drop_table('post_mortem', schema='alert')
    op.drop_index('ix_analog_alert', table_name='historical_analog', schema='alert')
    op.drop_table('historical_analog', schema='alert')
    op.drop_index('ix_evidence_alert', table_name='evidence_chain', schema='alert')
    op.drop_table('evidence_chain', schema='alert')
    op.drop_index('ix_feedback_alert', table_name='analyst_feedback', schema='alert')
    op.drop_table('analyst_feedback', schema='alert')
    op.drop_index('ix_alert_rule_trigger_rule_triggered', table_name='alert_rule_trigger', schema='alert')
    op.drop_index('ix_alert_rule_trigger_cooldown', table_name='alert_rule_trigger', schema='alert')
    op.drop_table('alert_rule_trigger', schema='alert')
    op.drop_table('narrative_cluster_articles')
    op.drop_index('ix_alert_status', table_name='alert', schema='alert')
    op.drop_index('ix_alert_severity', table_name='alert', schema='alert')
    op.drop_index('ix_alert_created', table_name='alert', schema='alert')
    op.drop_table('alert', schema='alert')
    op.drop_index('ix_risk_metrics_portfolio_id', table_name='risk_metrics', schema='trading')
    op.drop_index('ix_risk_metrics_portfolio_date', table_name='risk_metrics', schema='trading')
    op.drop_table('risk_metrics', schema='trading')
    op.drop_index('ix_position_symbol', table_name='position', schema='trading')
    op.drop_index('ix_position_portfolio_symbol', table_name='position', schema='trading')
    op.drop_index('ix_position_portfolio_id', table_name='position', schema='trading')
    op.drop_table('position', schema='trading')
    op.drop_index('ix_order_symbol', table_name='order', schema='trading')
    op.drop_index('ix_order_status', table_name='order', schema='trading')
    op.drop_index('ix_order_portfolio_id', table_name='order', schema='trading')
    op.drop_index('ix_order_created_at', table_name='order', schema='trading')
    op.drop_table('order', schema='trading')
    op.drop_index('ix_anomaly_flag', table_name='anomaly_result', schema='signal')
    op.drop_index('ix_anomaly_ensemble', table_name='anomaly_result', schema='signal')
    op.drop_table('anomaly_result', schema='signal')
    op.drop_index(op.f('ix_prediction_results_prediction_timestamp'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_model_id'), table_name='prediction_results')
    op.drop_index('idx_prediction_results_model_timestamp', table_name='prediction_results')
    op.drop_index('idx_prediction_results_horizon', table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index('ix_norm_source_time', table_name='normalized_event', schema='ingestion')
    op.drop_index('ix_norm_entity_value', table_name='normalized_event', schema='ingestion')
    op.drop_index('ix_norm_entity_time', table_name='normalized_event', schema='ingestion')
    op.drop_table('normalized_event', schema='ingestion')
    op.drop_index('ix_news_source', table_name='news_articles', schema='ingestion')
    op.drop_index('ix_news_published', table_name='news_articles', schema='ingestion')
    op.drop_table('news_articles', schema='ingestion')
    op.drop_index(op.f('ix_trend_time_series_timestamp'), table_name='trend_time_series')
    op.drop_index(op.f('ix_trend_time_series_keyword_id'), table_name='trend_time_series')
    op.drop_index(op.f('ix_trend_time_series_geo'), table_name='trend_time_series')
    op.drop_index('idx_trend_time_series_keyword_timestamp', table_name='trend_time_series')
    op.drop_index('idx_trend_time_series_geo_timestamp', table_name='trend_time_series')
    op.drop_table('trend_time_series')
    op.drop_index(op.f('ix_trend_alerts_keyword_id'), table_name='trend_alerts')
    op.drop_index(op.f('ix_trend_alerts_geo'), table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_type_triggered', table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_severity', table_name='trend_alerts')
    op.drop_index('idx_trend_alerts_keyword_triggered', table_name='trend_alerts')
    op.drop_table('trend_alerts')
    op.drop_index('ix_portfolio_user_id', table_name='portfolio', schema='trading')
    op.drop_index('ix_portfolio_is_active', table_name='portfolio', schema='trading')
    op.drop_table('portfolio', schema='trading')
    op.drop_index('ix_signal_source_bucket', table_name='signal_time_series', schema='signal')
    op.drop_index('ix_signal_entity_time', table_name='signal_time_series', schema='signal')
    op.drop_table('signal_time_series', schema='signal')
    op.drop_table('semantic_cluster_member', schema='signal')
    op.drop_index(op.f('ix_prediction_models_keyword_id'), table_name='prediction_models')
    op.drop_index('idx_prediction_models_type_version', table_name='prediction_models')
    op.drop_index('idx_prediction_models_keyword_active', table_name='prediction_models')
    op.drop_table('prediction_models')
    op.drop_table('narrative_saturation')
    op.drop_table('narrative_alerts')
    op.drop_index('ix_raw_source_time', table_name='raw_ingestion', schema='ingestion')
    op.drop_table('raw_ingestion', schema='ingestion')
    op.drop_index('ix_snapshot_session_time', table_name='replay_snapshot', schema='alert')
    op.drop_table('replay_snapshot', schema='alert')
    op.drop_index('ix_replay_signal_time', table_name='replay_signal', schema='alert')
    op.drop_index('ix_replay_signal_session', table_name='replay_signal', schema='alert')
    op.drop_index('ix_replay_signal_entity', table_name='replay_signal', schema='alert')
    op.drop_table('replay_signal', schema='alert')
    op.drop_index('ix_alert_rule_analytics_rule_id', table_name='alert_rule_analytics', schema='alert')
    op.drop_index('ix_alert_rule_analytics_period', table_name='alert_rule_analytics', schema='alert')
    op.drop_table('alert_rule_analytics', schema='alert')
    op.drop_index(op.f('ix_trend_snapshots_geo'), table_name='trend_snapshots')
    op.drop_index('idx_trend_snapshots_geo_captured', table_name='trend_snapshots')
    op.drop_index('idx_trend_snapshots_captured', table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_trend_keywords_keyword'), table_name='trend_keywords')
    op.drop_index(op.f('ix_trend_keywords_geo'), table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_last_seen', table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_keyword_geo', table_name='trend_keywords')
    op.drop_index('idx_trend_keywords_category', table_name='trend_keywords')
    op.drop_table('trend_keywords')
    op.drop_index('ix_cluster_drift', table_name='semantic_cluster', schema='signal')
    op.drop_table('semantic_cluster', schema='signal')
    op.drop_table('scheduled_reports')
    op.drop_table('report_templates')
    op.drop_table('narrative_clusters')
    op.drop_index('ix_market_data_timestamp', table_name='market_data')
    op.drop_index('ix_market_data_symbol_timestamp', table_name='market_data')
    op.drop_index('ix_market_data_symbol', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('source_registry', schema='ingestion')
    op.drop_index('ix_backtest_status', table_name='backtest_run', schema='backtest')
    op.drop_table('backtest_run', schema='backtest')
    op.drop_index('ix_alert_template_name', table_name='alert_template')
    op.drop_index('ix_alert_template_is_default', table_name='alert_template')
    op.drop_table('alert_template')
    op.drop_index('ix_user_username', table_name='user', schema='alert')
    op.drop_index('ix_user_email', table_name='user', schema='alert')
    op.drop_table('user', schema='alert')
    op.drop_index('ix_replay_user', table_name='replay_session', schema='alert')
    op.drop_index('ix_replay_time_range', table_name='replay_session', schema='alert')
    op.drop_index('ix_replay_status', table_name='replay_session', schema='alert')
    op.drop_table('replay_session', schema='alert')
    op.drop_index('ix_alert_rule_enabled', table_name='alert_rule', schema='alert')
    op.drop_index('ix_alert_rule_condition_type', table_name='alert_rule', schema='alert')
    op.drop_table('alert_rule', schema='alert')
    # ### end Alembic commands ###
