"""add_replay_mode_tables

Revision ID: c8745fb60119
Revises: cc502b28cbf2
Create Date: 2026-02-09 21:53:26.350672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8745fb60119'
down_revision: Union[str, None] = 'cc502b28cbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_session',
    sa.Column('user_id', sa.String(length=256), nullable=False, comment='User who created this replay session'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Descriptive name for the replay session'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of replay purpose'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Start of replay time window'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='End of replay time window'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Replay parameters: confidence_thresholds, detector_weights, etc.'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: created, running, completed, failed'),
    sa.Column('progress_percentage', sa.Float(), nullable=True, comment='Progress through the replay (0.0-1.0)'),
    sa.Column('alerts_generated', sa.Integer(), nullable=False, comment='Number of alerts that would have been generated'),
    sa.Column('trades_simulated', sa.Integer(), nullable=False, comment='Number of trades that would have been executed'),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Key insights from the replay analysis'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User who created this record'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User who last updated this record'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert'
    )
    op.create_index('ix_replay_session_status', 'replay_session', ['status'], unique=False, schema='alert')
    op.create_index('ix_replay_session_time_range', 'replay_session', ['start_time', 'end_time'], unique=False, schema='alert')
    op.create_index('ix_replay_session_user', 'replay_session', ['user_id'], unique=False, schema='alert')
    op.create_table('replay_snapshot',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False, comment='Point in time this snapshot represents'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Sequential order within the replay session'),
    sa.Column('active_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Active signals at this point: [{\'entity\': str, \'score\': float, ...}]'),
    sa.Column('system_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='System parameters at this time (thresholds, weights, etc.)'),
    sa.Column('market_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Market conditions snapshot (volatility, trends, etc.)'),
    sa.Column('portfolio_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Portfolio state: positions, cash, P&L, etc.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User who created this record'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User who last updated this record'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert'
    )
    op.create_index('ix_replay_snapshot_session_time', 'replay_snapshot', ['session_id', 'snapshot_time'], unique=False, schema='alert')
    op.create_table('replay_decision',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=False, comment='When this decision was made in replay time'),
    sa.Column('decision_type', sa.String(length=32), nullable=False, comment='Type: alert_generated, trade_executed, parameter_changed, etc.'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Sequential order within the replay session'),
    sa.Column('decision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Decision-specific data (alert details, trade parameters, etc.)'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score associated with this decision'),
    sa.Column('original_alert_id', sa.UUID(), nullable=True),
    sa.Column('original_trade_id', sa.UUID(), nullable=True),
    sa.Column('would_have_occurred', sa.Boolean(), nullable=True, comment='Whether this decision would have occurred in reality'),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Analysis of decision impact (P&L, risk, etc.)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User who created this record'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User who last updated this record'),
    sa.ForeignKeyConstraint(['original_alert_id'], ['alert.alert.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_trade_id'], ['trading.order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert'
    )
    op.create_index('ix_replay_decision_session_time', 'replay_decision', ['session_id', 'decision_time'], unique=False, schema='alert')
    op.create_index('ix_replay_decision_type', 'replay_decision', ['decision_type'], unique=False, schema='alert')
    op.create_table('replay_signal',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('entity_value', sa.String(length=1024), nullable=False, comment='The entity this signal is about'),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False, comment='When this signal occurred'),
    sa.Column('original_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Original anomaly scores from detectors'),
    sa.Column('adjusted_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Scores after applying replay parameters'),
    sa.Column('would_trigger_alert', sa.Boolean(), nullable=False, comment='Whether this signal would trigger an alert with current parameters'),
    sa.Column('confidence_level', sa.Float(), nullable=False, comment='Final confidence score (0.0-1.0)'),
    sa.Column('signal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional signal metadata (source, trend data, etc.)'),
    sa.Column('parameter_sensitivity', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='How sensitive this signal is to parameter changes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Globally unique row identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=256), nullable=True, comment='User who created this record'),
    sa.Column('updated_by', sa.String(length=256), nullable=True, comment='User who last updated this record'),
    sa.ForeignKeyConstraint(['session_id'], ['alert.replay_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='alert'
    )
    op.create_index('ix_replay_signal_entity', 'replay_signal', ['entity_value'], unique=False, schema='alert')
    op.create_index('ix_replay_signal_session', 'replay_signal', ['session_id'], unique=False, schema='alert')
    op.create_index('ix_replay_signal_time', 'replay_signal', ['signal_time'], unique=False, schema='alert')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_replay_signal_time', table_name='replay_signal', schema='alert')
    op.drop_index('ix_replay_signal_session', table_name='replay_signal', schema='alert')
    op.drop_index('ix_replay_signal_entity', table_name='replay_signal', schema='alert')
    op.drop_table('replay_signal', schema='alert')
    op.drop_index('ix_replay_decision_type', table_name='replay_decision', schema='alert')
    op.drop_index('ix_replay_decision_session_time', table_name='replay_decision', schema='alert')
    op.drop_table('replay_decision', schema='alert')
    op.drop_index('ix_replay_snapshot_session_time', table_name='replay_snapshot', schema='alert')
    op.drop_table('replay_snapshot', schema='alert')
    op.drop_index('ix_replay_session_time_range', table_name='replay_session', schema='alert')
    op.drop_index('ix_replay_session_status', table_name='replay_session', schema='alert')
    op.drop_index('ix_replay_session_user', table_name='replay_session', schema='alert')
    op.drop_table('replay_session', schema='alert')
    # ### end Alembic commands ###
