"""Add alert templates table

Revision ID: c9309228e88c
Revises: ab83ab279b01
Create Date: 2026-02-09 07:58:20.993122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9309228e88c'
down_revision: Union[str, None] = 'ab83ab279b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_template',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by', sa.String(length=256), nullable=True),
        sa.Column('updated_by', sa.String(length=256), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('subject_template', sa.String(length=255), nullable=False),
        sa.Column('html_template', sa.Text(), nullable=False),
        sa.Column('text_template', sa.Text(), nullable=False),
        sa.Column('severity_filter', sa.JSON(), nullable=True),
        sa.Column('category_filter', sa.JSON(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('template_metadata', sa.JSON(), nullable=True),
        sa.Index('ix_alert_template_name', 'name'),
        sa.Index('ix_alert_template_is_default', 'is_default'),
        schema='alert',
        comment='Customizable alert notification templates'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_template', schema='alert')
    # ### end Alembic commands ###
