"""Email notifier via SMTP with HTML templates."""

from __future__ import annotations

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from .base import BaseNotifier

logger = logging.getLogger(__name__)


class EmailNotifier(BaseNotifier):
    """Sends alert emails via SMTP (supports TLS) with HTML templates."""

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        username: str,
        password: str,
        from_addr: str,
        to_addrs: list[str],
        use_tls: bool = True,
        template_dir: str | None = None,
    ) -> None:
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_addr = from_addr
        self.to_addrs = to_addrs
        self.use_tls = use_tls

        # Setup Jinja2 template environment
        if template_dir is None:
            # Default to templates directory relative to this file
            template_dir = Path(__file__).parent / "templates"
        self.template_env = Environment(
            loader=FileSystemLoader(template_dir),
            autoescape=True
        )

    def _render_template(self, template_name: str, context: dict[str, Any]) -> str:
        """Render a Jinja2 template with the given context."""
        try:
            template = self.template_env.get_template(template_name)
            return template.render(**context)
        except Exception as e:
            logger.error("Failed to render email template %s: %s", template_name, e)
            return ""

    def _create_plain_text_fallback(self, alert: dict[str, Any]) -> str:
        """Create a plain text version of the alert email."""
        severity = alert.get("severity", "medium").upper()
        term = alert.get("term", "Unknown")
        score = alert.get("anomaly_score", 0)
        confidence = alert.get("confidence_score", 0)

        body = f"""Vanguard Signal Alert - {severity} Priority

Term: {term}
Anomaly Score: {score:.3f}
Confidence: {confidence:.1%}
Source: {alert.get('source', 'N/A')}
Detected At: {alert.get('detected_at', 'N/A')}

{alert.get('summary_text', '')}

View in Dashboard: {alert.get('dashboard_url', 'http://localhost:3000')}
Acknowledge Alert: {alert.get('acknowledge_url', 'http://localhost:3000/alerts')}

This alert was automatically generated by Vanguard Signal trend detection system.
"""
        return body

    async def send(self, alert: dict[str, Any]) -> bool:
        """Send HTML email with plain text fallback."""
        severity = alert.get("severity", "medium").upper()
        term = alert.get("term", "Unknown")

        # Check if we have pre-rendered template content
        template_content = alert.get("template_content")
        if template_content:
            subject = template_content.get("subject", f"[Vanguard Signal] {severity} Alert — {term}")
            html_content = template_content.get("html", "")
            text_content = template_content.get("text", "")
        else:
            # Fallback to legacy template rendering
            subject = f"[Vanguard Signal] {severity} Alert — {term}"

            # Prepare template context
            context = {
                "severity": severity,
                "term": term,
                "anomaly_score": f"{alert.get('anomaly_score', 0):.3f}",
                "confidence": f"{alert.get('confidence_score', 0) * 100:.1f}",
                "source": alert.get("source", "N/A"),
                "detected_at": alert.get("detected_at", "N/A"),
                "summary": alert.get("summary_text", ""),
                "reason_code": alert.get("reason_code", ""),
                "dashboard_url": alert.get("dashboard_url", "http://localhost:3000"),
                "acknowledge_url": alert.get("acknowledge_url", "http://localhost:3000/alerts"),
                "resolve_url": alert.get("resolve_url", "http://localhost:3000/alerts"),
            }

            # Render HTML content
            html_content = self._render_template("alert_email.html", context)

            # Create plain text fallback
            text_content = self._create_plain_text_fallback(alert)

        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.from_addr
        msg["To"] = ", ".join(self.to_addrs)

        # Attach both plain text and HTML versions
        text_part = MIMEText(text_content, "plain")
        html_part = MIMEText(html_content, "html")

        msg.attach(text_part)
        msg.attach(html_part)

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                server.login(self.username, self.password)
                server.sendmail(self.from_addr, self.to_addrs, msg.as_string())
            return True
        except Exception:
            logger.exception("Email notification failed")
            return False

        msg = MIMEText(body, "plain")
        msg["Subject"] = subject
        msg["From"] = self.from_addr
        msg["To"] = ", ".join(self.to_addrs)

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                server.login(self.username, self.password)
                server.sendmail(self.from_addr, self.to_addrs, msg.as_string())
            return True
        except Exception:
            logger.exception("Email notification failed")
            return False
