"""
base.py — Base strategy classes and data structures.

Provides the foundation for all trading strategies with standardized
interfaces for signal generation, risk management, and performance tracking.
"""

from __future__ import annotations

import abc
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional, Protocol, Union
from enum import Enum


class SignalType(Enum):
    """Types of trading signals that strategies can generate."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


class StrategyType(Enum):
    """Categories of trading strategies."""
    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    ARBITRAGE = "arbitrage"
    MOMENTUM = "momentum"
    BREAKOUT = "breakout"
    PORTFOLIO = "portfolio"
    MACHINE_LEARNING = "machine_learning"


@dataclass
class StrategyConfig:
    """Configuration for a trading strategy."""

    # Basic identification
    strategy_id: str
    name: str
    description: str = ""
    strategy_type: StrategyType = StrategyType.TREND_FOLLOWING

    # Risk management
    max_position_size: Decimal = Decimal("0.1")  # Max 10% of portfolio
    max_drawdown_limit: Decimal = Decimal("0.2")  # Max 20% drawdown
    stop_loss_pct: Optional[Decimal] = Decimal("0.05")  # 5% stop loss
    take_profit_pct: Optional[Decimal] = None

    # Trading parameters
    symbols: List[str] = field(default_factory=list)  # Symbols to trade
    min_signal_strength: Decimal = Decimal("0.6")  # Minimum signal confidence
    max_positions: int = 5  # Maximum concurrent positions

    # Strategy-specific parameters
    parameters: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    version: str = "1.0.0"
    author: str = "Intel-AI"
    created_at: datetime = field(default_factory=lambda: datetime.now())
    updated_at: datetime = field(default_factory=lambda: datetime.now())

    def __post_init__(self):
        if not self.symbols:
            self.symbols = ["SPY", "QQQ", "IWM", "TLT", "GLD"]  # Default universe


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    symbol: str
    signal_type: SignalType
    strength: Decimal  # 0.0 to 1.0 confidence level
    price: Optional[Decimal] = None
    quantity: Optional[Decimal] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now())
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not (0 <= self.strength <= 1):
            raise ValueError("Signal strength must be between 0.0 and 1.0")


@dataclass
class StrategyResult:
    """Result from executing a strategy."""

    strategy_id: str
    signals: List[Signal] = field(default_factory=list)
    portfolio_value: Optional[Decimal] = None
    positions_count: int = 0
    timestamp: datetime = field(default_factory=lambda: datetime.now())

    # Performance metrics
    total_return: Decimal = Decimal("0.0")
    sharpe_ratio: Optional[Decimal] = None
    max_drawdown: Decimal = Decimal("0.0")
    win_rate: Decimal = Decimal("0.0")

    # Risk metrics
    volatility: Optional[Decimal] = None
    value_at_risk: Optional[Decimal] = None

    # Execution details
    execution_time_ms: int = 0
    errors: List[str] = field(default_factory=list)


class MarketDataProtocol(Protocol):
    """Protocol for market data access."""

    async def get_price(self, symbol: str) -> Optional[Decimal]:
        """Get current price for a symbol."""
        ...

    async def get_historical_prices(
        self,
        symbol: str,
        start_date: datetime,
        end_date: datetime
    ) -> Dict[datetime, Decimal]:
        """Get historical price data."""
        ...


class PortfolioProtocol(Protocol):
    """Protocol for portfolio access."""

    @property
    def cash_balance(self) -> Decimal:
        """Available cash balance."""
        ...

    @property
    def total_value(self) -> Decimal:
        """Total portfolio value."""
        ...

    def get_position(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Get position details for a symbol."""
        ...

    def get_positions(self) -> List[Dict[str, Any]]:
        """Get all positions."""
        ...


class BaseStrategy(abc.ABC):
    """
    Abstract base class for all trading strategies.

    Strategies should inherit from this class and implement the
    generate_signals method with their specific trading logic.
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.strategy_id = config.strategy_id
        self.logger = None  # Will be set by strategy runner

    @abc.abstractmethod
    async def generate_signals(
        self,
        market_data: MarketDataProtocol,
        portfolio: PortfolioProtocol
    ) -> List[Signal]:
        """
        Generate trading signals based on market data and portfolio state.

        This is the main method that strategies must implement with their
        specific trading logic (technical analysis, statistical models, etc.).

        Args:
            market_data: Access to current and historical market data
            portfolio: Access to current portfolio state

        Returns:
            List of trading signals to execute
        """
        pass

    @abc.abstractmethod
    def validate_config(self) -> List[str]:
        """
        Validate strategy configuration.

        Returns a list of error messages if configuration is invalid.
        Returns empty list if configuration is valid.
        """
        errors = []

        if not self.config.symbols:
            errors.append("At least one symbol must be specified")

        if not (0 < self.config.max_position_size <= 1):
            errors.append("max_position_size must be between 0 and 1")

        if self.config.max_drawdown_limit <= 0:
            errors.append("max_drawdown_limit must be positive")

        return errors

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        return self.config.parameters.copy()

    def update_parameters(self, parameters: Dict[str, Any]) -> None:
        """Update strategy parameters."""
        self.config.parameters.update(parameters)
        self.config.updated_at = datetime.now()

    def get_metadata(self) -> Dict[str, Any]:
        """Get strategy metadata for serialization."""
        return {
            "strategy_id": self.strategy_id,
            "name": self.config.name,
            "description": self.config.description,
            "type": self.config.strategy_type.value,
            "version": self.config.version,
            "author": self.config.author,
            "parameters": self.get_parameters(),
        }

    def __str__(self) -> str:
        return f"{self.config.name} ({self.strategy_id})"

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(config={self.config!r})"